// TODO: [API] GET /api/questions
import type { Question } from "@/types";

export const mockQuestions: Question[] = [
  {
    id: "q-1",
    type: "multiple_choice",
    body: "Qual é o resultado da expressão 2³ + 4²?",
    baseText: null,
    discipline: "Matemática",
    tags: ["potenciação", "expressões numéricas"],
    bnccCode: "EF09MA01",
    yearLevel: "9º Ano",
    difficulty: "easy",
    source: "personal",
    options: [
      { id: "q1-a", label: "A", text: "20", isCorrect: false },
      { id: "q1-b", label: "B", text: "24", isCorrect: true },
      { id: "q1-c", label: "C", text: "18", isCorrect: false },
      { id: "q1-d", label: "D", text: "32", isCorrect: false },
      { id: "q1-e", label: "E", text: "16", isCorrect: false },
    ],
  },
  {
    id: "q-2",
    type: "multiple_choice",
    body: "Em um triângulo retângulo, os catetos medem 3 cm e 4 cm. Qual é a medida da hipotenusa?",
    baseText: null,
    discipline: "Matemática",
    tags: ["teorema de pitágoras", "geometria"],
    bnccCode: "EF09MA09",
    yearLevel: "9º Ano",
    difficulty: "medium",
    source: "ai_generated",
    options: [
      { id: "q2-a", label: "A", text: "5 cm", isCorrect: true },
      { id: "q2-b", label: "B", text: "7 cm", isCorrect: false },
      { id: "q2-c", label: "C", text: "25 cm", isCorrect: false },
      { id: "q2-d", label: "D", text: "6 cm", isCorrect: false },
      { id: "q2-e", label: "E", text: "3,5 cm", isCorrect: false },
    ],
  },
  {
    id: "q-3",
    type: "discursive",
    body: "Explique a diferença entre mitose e meiose, indicando em quais situações cada processo ocorre no organismo humano.",
    baseText: "A divisão celular é um processo fundamental para o crescimento, reprodução e renovação dos tecidos nos seres vivos.",
    discipline: "Ciências",
    tags: ["divisão celular", "biologia"],
    bnccCode: "EF09CI07",
    yearLevel: "9º Ano",
    difficulty: "hard",
    source: "personal",
    options: [],
  },
  {
    id: "q-4",
    type: "multiple_choice",
    body: "Qual figura de linguagem está presente no verso: 'A vida é bela como uma flor'?",
    baseText: null,
    discipline: "Português",
    tags: ["figuras de linguagem", "literatura"],
    bnccCode: "EF69LP48",
    yearLevel: "8º Ano",
    difficulty: "easy",
    source: "public",
    options: [
      { id: "q4-a", label: "A", text: "Metáfora", isCorrect: false },
      { id: "q4-b", label: "B", text: "Metonímia", isCorrect: false },
      { id: "q4-c", label: "C", text: "Simile (comparação)", isCorrect: true },
      { id: "q4-d", label: "D", text: "Ironia", isCorrect: false },
      { id: "q4-e", label: "E", text: "Hipérbole", isCorrect: false },
    ],
  },
  {
    id: "q-5",
    type: "multiple_choice",
    body: "Quais são os produtos da fotossíntese?",
    baseText: "A fotossíntese é o processo pelo qual plantas, algas e algumas bactérias convertem energia luminosa em energia química.",
    discipline: "Ciências",
    tags: ["fotossíntese", "plantas"],
    bnccCode: "EF07CI08",
    yearLevel: "7º Ano",
    difficulty: "medium",
    source: "ai_generated",
    options: [
      { id: "q5-a", label: "A", text: "CO₂ e H₂O", isCorrect: false },
      { id: "q5-b", label: "B", text: "Glicose e O₂", isCorrect: true },
      { id: "q5-c", label: "C", text: "Glicose e CO₂", isCorrect: false },
      { id: "q5-d", label: "D", text: "O₂ e H₂O", isCorrect: false },
      { id: "q5-e", label: "E", text: "ATP e H₂O", isCorrect: false },
    ],
  },
];
